---
- name: Full upgrade
  hosts: virtualmachines
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: "yes"
        cache_valid_time: 3600
    - name: Perform full upgrade
      ansible.builtin.apt:
        upgrade: "full"
    - name: Check the reboot-required file
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Perform reboot if needed
      ansible.builtin.reboot:
        msg: "Performing reboot with ansible."
      when: reboot_required_file.stat.exists == "true"
