---
- name: Update all packages
  hosts: virtualmachines
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: "yes"
        cache_valid_time: 3600
    - name: Update all packages
      ansible.builtin.apt:
        upgrade: "yes"
